language: c
compiler: gcc
sudo: false
dist: trusty

env:
  - TARGET=x86_64-linux-musl
  - TARGET=i486-linux-musl
  - TARGET=aarch64-linux-musl
  - TARGET=arm-linux-musleabi
  - TARGET=arm-linux-musleabihf

install:
  - openssl aes-256-cbc -K $OPENSSL_KEY -iv $OPENSSL_IV -in just-containers/keys.tar.xz.enc -out just-containers/keys.tar.xz -d
  - tar xf just-containers/keys.tar.xz -C just-containers
  - gpg --import just-containers/keys/public.key
  - gpg --allow-secret-key-import --import just-containers/keys/private.key

script:
  - bash just-containers/build ${TARGET}

after_success:
  - bash just-containers/upload
